// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jxfqimwgyureainctqjl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp4ZnFpbXdneXVyZWFpbmN0cWpsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg2MTA2NDIsImV4cCI6MjA3NDE4NjY0Mn0.-J5J9p2u-Kc6XuMmeYaqdvCJ8crPhxCpN-8wRpNiAks";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});